In [37]:
import numpy as np
A = np.ones((2, 10))
B = np.array((3,6,7))

In [28]:
A

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [30]:
B

array([3, 6, 7])

In [12]:
A[0,2] = 5
A[1,3] = 7

In [20]:
B.shape[0]

3

In [38]:
A[0:1,5:8] = B

In [39]:
A

array([[1., 1., 1., 1., 1., 3., 6., 7., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [40]:
len(B)

3

In [41]:
2**8

256

In [43]:
'0'*5*2

'0000000000'

In [44]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
import numpy as np
R = np.array((2, 2, 4, 5, 0))
np.diff(R)

array([ 0,  2,  1, -5])