In [15]:
import numpy as np
A = np.ones((2, 10))
B = np.array((3,6,7))

In [16]:
A

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
B

array([3, 6, 7])

In [18]:
A[0,2] = 5
A[1,3] = 7

In [19]:
B.shape[0]

3

In [20]:
A

array([[1., 1., 5., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 7., 1., 1., 1., 1., 1., 1.]])

In [21]:
A[0:1,5:8] = B

In [22]:
A

array([[1., 1., 5., 1., 1., 3., 6., 7., 1., 1.],
       [1., 1., 1., 7., 1., 1., 1., 1., 1., 1.]])

In [23]:
len(B)

3

In [27]:
list(range(0, 5, 2))

[0, 2, 4]

In [29]:
for k in range(10):
    i = k//2
    a0 = i & 0x01
    a1 = i & 0x02
    a2 = i & 0x04
    print(k, a2, a1, a0)

0 0 0 0
1 0 0 0
2 0 0 1
3 0 0 1
4 0 2 0
5 0 2 0
6 0 2 1
7 0 2 1
8 4 0 0
9 4 0 0


In [34]:
2**20/17

61680.94117647059