In [15]:
import numpy as np
A = np.ones((2, 10))
B = np.array((3,6,7))

In [16]:
A

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
B

array([3, 6, 7])

In [18]:
A[0,2] = 5
A[1,3] = 7

In [19]:
B.shape[0]

3

In [20]:
A

array([[1., 1., 5., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 7., 1., 1., 1., 1., 1., 1.]])

In [21]:
A[0:1,5:8] = B

In [22]:
A

array([[1., 1., 5., 1., 1., 3., 6., 7., 1., 1.],
       [1., 1., 1., 7., 1., 1., 1., 1., 1., 1.]])

In [23]:
len(B)

3

In [27]:
list(range(0, 5, 2))

[0, 2, 4]